### ISSUE TITLE
destory()

### ISSUE THREAD

**Issue by puppetMaster3** [vissense/vissense#29]
Hi,
Is there a destroy() or a cleanup() method?

I dynamically load sub modules of html and need to reload sometimes.

**Comment by theborakompanioni** [comment]
You can stop a monitor in a clean way with `myMonitor.stop()`. See  http://vissense.github.io/vissense/VisSense.VisMon.html#stop
Does this help you?

**Comment by puppetMaster3** [comment]
I'll try and let you know

**Comment by theborakompanioni** [comment]
Alright. Let me know if you need any help!

**Comment by puppetMaster3** [comment]
Works w/o any destroy or clean up, it just runs again ok. (some .js runs second time a mess)

**Comment by theborakompanioni** [comment]
@puppetMaster3 I cannot figure out what you are trying to tell me :)

**Comment by puppetMaster3** [comment]
1. It works, I can just leave the page.

(2. but some other projects don't work when you load html/js module 2 times).
