### ISSUE TITLE
Should detect elements out of viewport in a container with overflow:hidden as hidden

### ISSUE THREAD

**Issue by theborakompanioni** [vissense/vissense#3]
e.g.
```
<div style="width:0; overflow:hidden">
  <span id="myElement"></span>
</div>
```
```
VisSense(document.getElementyById('myElement')).isVisible(); // => true

```

**Comment by AlchemyUnited** [comment]
I'm curious. Do you consider this one single bug? Or two different ones? Maybe this, at least in part, falls under "detect if an element is overlapped by others"?

**Comment by theborakompanioni** [comment]
@AlchemyUnited You are absolutely right - thank you for paying attention so carefully. Of course the terminology is wrong because in this example no element is "overlapped" by another - but the reason is the same. This is why this issue has not been tackled in the last month - it just serves as a personal reminder that this may need to be looked at in future development cycles.

Another thing that strikes me is that the parent element has "width:0". So in a way, if it is still a valid example, it is in fact a bug. I am going to revalidate it - thank you for bringing it to my attention.

**Comment by AlchemyUnited** [comment]
The question i have have is, to fix it feels - off the top of my head - expensive in terms of processing, fringe cases, etc. It does kinda feel like something that we should know without having to calculate. But maybe said complexity is why no one has asked / bothered up til now? :)

**Comment by AlchemyUnited** [comment]
At the very least the outside viewport feels like a true bug. I meanm regardless of the div wrapper, etc. it's still not visible, yes?

**Comment by theborakompanioni** [comment]
@AlchemyUnited I am not quite sure I understand what you mean. If you mean that the element should not be detected as "visible" if it is inside a container which is not in the current viewport of the browser then: Yes - this is handled correctly.

**Comment by theborakompanioni** [comment]
@AlchemyUnited Verified that elements with parents without width/height are hidden. Closing this issue since the other case falls in the category "What it does not: detect if an element is overlapped by others".

**Comment by AlchemyUnited** [comment]
Nice!
