### ISSUE TITLE
common js

### ISSUE THREAD

**Issue by curioussavage** [vissense/vissense#30]
Is supporting CommonJS something you have considered? Biased opinion here, but finding a useful JS library that doesn't support it and isn't on NPM is weird these days. Once you use Browserify or Webpack its hard to go back

**Comment by curioussavage** [comment]
oops, just saw the umd template. However the version in dist is built with the not conflicts template adding extra steps for use with browserify. Is there a version built with the umd template on npm? I can't seem to find one?

**Comment by theborakompanioni** [comment]
@curioussavage I guess I can incorporate the "no-conflict" style version into the umd template. Browserify would then work as expected, would it?

**Comment by theborakompanioni** [comment]
@curioussavage No, currently there is no version on npm. I will do it beginning with v0.9.0. Thank you for pointing it out! Can you confim compatability of [v0.9.0-alpha1](https://github.com/vissense/vissense/releases/tag/0.9.0-alpha1) with browserify?

**Comment by curioussavage** [comment]
import worked just fine!

**Comment by curioussavage** [comment]
ok, sat down to actually use it in my app and there is an issue. Can't get a stack trace with un minified code because Browserify won't build with the unminified version, give me some useless error pointing at a line that is fine. Gah :frowning:  pretty tired now so I will give it another try tomorrow if it isn't solved already.

**Comment by theborakompanioni** [comment]
@curioussavage Thank you for your efforts. Much appreciated! Looking forward to hearing back from you about this issue. Reach out to me if you have any problems. I am here to help.

**Comment by curioussavage** [comment]
I was probably just drowzy and did something wrong last night because it is working perfectly!

**Comment by theborakompanioni** [comment]
@curioussavage Nice! I will publish v0.9.0 soon and put it in the npm registry. I also have to update the plugin mechanism for the plugins to be compatible with the `require` syntax. I guess that's long overdue.

If you have any further questions or need some advice - let me know.

**Comment by theborakompanioni** [comment]
Finally. See https://www.npmjs.com/package/vissense
