### ISSUE TITLE
Does this thrash layout?

### ISSUE THREAD

**Issue by davidosomething** [vissense/vissense#36]
getBoundingClientRect calls and others used by this repo are known to thrash layout:
http://ricostacruz.com/cheatsheets/layout-thrashing.html

Would it help offload computation to `requestIdleCallback` / `requestAnimationFrame`?

**Comment by theborakompanioni** [comment]
I see no way around using layout effecting methods when determining the visibility of an element. Do you have any ideas?

Regarding `requestAnimationFrame`: #24 has been proposed but not implemented. Maybe it's time to revisit that task.
