### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by klihelp** [vissense/vissense#4]
Inline code documentation could benefit users, including you, to help read understand and use your code.
I suggest to use JSDoc
https://github.com/jsdoc3/jsdoc

Also the tutorials / demos need more example codes. 
eg. couldn't find the usage code for Track Section Demo

Thank you for this nice plugin.
Previously I played with jQuery.inView and Waypoints with Inview plugin.

**Comment by theborakompanioni** [comment]
Currently this project uses Docular (http://grunt-docular.com/) for documentation generation - but I am slightly annoyed by it. I may consider switching to jsdoc - thanks for the suggestion.

You are absolutely right - the tutorial needs better descriptions and more code examples.
The thing is, the examples are all very simple and basically the "Track Section Demo" is the same as "Draggable Element Demo" - but I will definitely add more stuff when I have time.

One thing though:
"Inline code documentation could benefit users, including you, to help read understand and use your code." -> do you think the documentation is still unsufficient?

Nonetheless, thanks for your comment.

**Comment by klihelp** [comment]
Yes, for first time users needs the basic documentation. 
And by experience you will need a refresh if you dont touch the code after a while.

Took some time to figure out public events, functions, passed arguments to callbacks.
from the non-minified source code.
Your demos are excellent, shows what's possible to achieve with the project.
Glad to help if I can. Good luck with the documentation to help new users replicate your demos.

I liked Waypoints documentation, it was easy and didn't had to look into their source code.
http://imakewebthings.com/waypoints/
http://imakewebthings.com/waypoints/shortcuts/inview/

**Comment by theborakompanioni** [comment]
Waypoints web docs are pretty nice - I'll consider it as a role model for the demo page. Thank you.
Anyway, if you have time and resources I'd be happy to invite you to fork https://github.com/vissense/vissense-demo and add some examples or missing pieces yourself.
This, of course, should not mean that you are obligated to do so, but I'd really love to see what other devs are creating with it. Maybe it's something I never had in mind!

**Comment by klihelp** [comment]
Thanks for your invitation:) forked
