### ISSUE TITLE
Get element inside monitor

### ISSUE THREAD

**Issue by vetash** [vissense/vissense#40]
Hello! Can you help me? 
I want to add class or other attribute to elements whenewer is visible. Is it possible? 
Something like that:
https://jsbin.com/zuponexita/1/edit?html,js,console,output

**Comment by theborakompanioni** [comment]
Hey @vetash! Sorry for the delayed reply.
Yes, you can obtain the element you watching from the monitor object.
```javascript
monitor.visobj().element()
```

Change your code from:
```javascript
  VisSense.VisMon.Builder(VisSense(myElements[i]))
    .on('fullyvisible', function(monitor) {
      console.log('VISIBLE!!!');
      this.className += "test2"
    })
    .build()
    .start();
```
to:
```javascript
  VisSense.VisMon.Builder(VisSense(myElements[i]))
    .on('fullyvisible', function(monitor) {
      console.log('VISIBLE!!!');
      monitor.visobj().element().className += " test2";
    })
    .build()
    .start();
```

Do you think it should be described in the docs?
I wonder whether it is justified to pull an `element()` function directly into monitor (being able to call `monitor.element()`).. what do you think?

Please tell me, whether this solved your problem.
Have a nice day.

**Comment by vetash** [comment]
Hello, @theborakompanioni ! Thank you for the reply. Yes your example works like a charm!
I'm sure this case should be in documentation. 
About `element` funtcion: if it possible to save compatibility with older release why not? 
Thank's again for the help!
