### ISSUE TITLE
How measure visibility of a group of elements using Vissense.js

### ISSUE THREAD

**Issue by Matso89** [vissense/vissense#44]
I have more than 10 videos in my page. (videos are very short, each about 5 seconds)
I want when 0.75 percent of each video get visible,  that video plays.

so I used below code:

```
	var timer;
	var vids = document.getElementsByTagName('video');
	$(window).scroll(function() {
		if(timer) {
			window.clearTimeout(timer);
		}
		timer = window.setTimeout(function() {
			for( var i = 0; i < vids.length; i++ ){
				if (VisSense(vids.item(i)).percentage() > 0.75) {
					vids.item(i).play();
				} else {
					vids.item(i).pause();
				}
			}
		}, 200);
	});
```

the above code works perfectly when there is just a single video in viewport.
but when there is more than a video in viewport, the code not works as expected and none of the videos get played.

What I need is:
Each video has visibility more than 0.75 percent must be played.
For i.e, if there are 3 videos in viewport and 2 of theme has visibility more than 0.75 percent so both videos must be played.

any help is appreciated
thanks

**Comment by theborakompanioni** [comment]
Here there. Sorry for the late reply.

Your code only checks the visiblity of your element once.
You'd need to monitor the visiblity over time and act as soon as the percentage is greater than 75 percent.
I think the code you are looking for is actually in the readme:
```js
var video = $('#video'); 
var visibility = VisSense(video[0], { fullyvisible: 0.75 });

var visibility_monitor = visibility.monitor({
  fullyvisible: function() { 
    video.play();
  }, 
  hidden: function() { 
    video.stop(); 
  }
}).start();
```

Hope this can guide you into the right direction. Reopen if necessary!
