### ISSUE TITLE
I want to use this code multiple video blocks

### ISSUE THREAD

**Issue by globalstar20112** [vissense/vissense#45]
Hello there,
could you please help me for that.
I want to use this code multiple video blocks.
So,
I have created this type of code.
Please fix it.

 ```
   function scrollVideoMob(elementId){
      var sectionElement = jQuery('#' + elementId);
      VisSense.VisMon.Builder(VisSense(sectionElement[0], { fullyvisible: 0.75 }))
      .on('fullyvisible', function(monitor) {
        sectionElement.play();
      })
      .on('hidden', function(monitor) {
        sectionElement.pause();

      })
      .build()
      .start();       
      
    }
    
    $(".desktop_vid_section .product__detail__media_inner_video").each(function(e){
      	var get_sectionElement = jQuery(this).attr("id");
      	scrollVideoMob(get_sectionElement);
        //alert($(this).text())
    });  
```

**Comment by malykh** [comment]
looking for the same solution. How to use this script with the page that has several videos?

**Comment by theborakompanioni** [comment]
@malykh Should be working as described above. You can specify the element you want to observe as first argument to `VisSense.VisMon.Builder`. You can always share some code examples of yours if it is not working as expected.
