### ISSUE TITLE
Not Working When styling fade

### ISSUE THREAD

**Issue by JoshuvaGeorge03** [vissense/vissense#46]
In my Image slideshow, when i set image style as fade, vissense not firing hidden events even though my img element is went out of viewport. if i set sliding as effect it work as intended.

Kindly help need a quick fix.

**Comment by JoshuvaGeorge03** [comment]
Kindly help, is this a bug or am i doing something wrong? kindly see below for my code.

                            const videoElement = document.querySelector('#videoEl') as HTMLVideoElement;
                            if (videoElement) {
                                VisSense.VisMon.Builder(VisSense(videoElement, { fullyvisible: 0.8 }))
                                    .on('fullyvisible', function (monitor) {
                                        videoElement.play();
                                    })
                                    .on('hidden', function (monitor) {
                                        videoElement.pause();

                                    })
                                    .build()
                                    .start();

**Comment by theborakompanioni** [comment]
@JoshuvaGeorge03 Sorry for the late reply. Your example code looks good to me.
Currently I have not enough time to investigate this thoroughly. Any help in investigating this issue would be awesome. Pull requests are welcome!
