### ISSUE TITLE
Exit and enter events for leaving and coming elements

### ISSUE THREAD

**Issue by klihelp** [vissense/vissense#5]
I managed to replicate the Track Section Demo.

I would like to monitor the sections and change the opacity for leaving elements.

Leaving element means that:
- element state is still visible or fullyvisible
- some of the element's edge is not visible, so pracatically not fully visible 
- over time the visibility percentage decreasing
1. How to fire once an Exit event when the element leaving reaching a specified visibility percentage?
2. How to fire once an Enter event when the element coming into view reaching a specified visibility percentage?
3. Monitoring direction would be helpful.

I would like to read your thoughts about it.
A possible API could be:

```
// Init VisSense
visobj = VisSense(this, {
   // Fully visible when 20% of the element visible on any side
   fullyvisible: 0.20,

// Set percentage for each direction
// - Single number would work for all direction, eg exit: 0.80
// - If a direction config missing, then get value from the opposite direction alue
// - if neather oposite direction not exists then get value from any or first direction value which is set
    exit: {
        top: 0.80,
        bottom: 0.20,
        left: 0.80,
        right: 0.20,
        },
    enter: {
        top: 0.60,
        bottom: 0.80,
        left: 0.60,
        right: 0.80,
        }
    }
});


/**
 * Elements Visibility Monitor
 */
var visibility_monitor = visobj.monitor({

    strategy: new VisSense.VisMon.Strategy.PollingStrategy(),

    exit: function(direction, me){

        console.log(direction)
        // possible direction values:
        // top, right, bottom, left
        // topright, topleft, bottomleft, bottomright

    },

    enter: function(direction, me){

        console.log(direction)
        // possible direction values:
        // top, right, bottom, left
        // topright, topleft, bottomleft, bottomright

    }

});
```

I think I can work out with percentagechange event, but requires some thoughts to figure out the base logic, in which I need your help.

**Comment by theborakompanioni** [comment]
I am really into the idea to include the scroll direction or a value indicating whether the element is above or below the viewport.

Everything else you have described would be better placed in a seperate plugin.
You can listen to "visibilitychange" events and fire enter/exit events yourself.
If you have any problem feel free to post again.

I will close this issue as soon as the "scroll direction" as been implemented.

**Comment by AlchemyUnited** [comment]
@theborakompanioni - Actually, I have some other bigger / broader ideas about what would be nice (read: #BadAss). Where would you like me to spit them? Here? Open a new topic? PM you? Email you? 

I'm not a js wizard so it's a bit above my pay grade but I'm been looking at Vissense,scrollReveal.js(https://github.com/julianlloyd/scrollReveal.js) as well as lazy loading. They all feel connected / related to me. That is, Vissense could also assist with (for example) lazy load if it were willing to track beyond the visible view port. 

It short, it's all about (x and y) position and scroll direction w/ viability being a subset (if you will) of location / direction. Solve the bigger problem (location + direction) and then (almost) anything location dependent seems possible.

If I could share these ideas, and perhaps be an apprentice for the coding, that would be great.

**Comment by theborakompanioni** [comment]
@AlchemyUnited Ideas are always welcome! Just open new issues and somebody (probably me) will take a look at it.

One thing though - VisSense.js has one purpose: Provide a convenient API for detecting visibility changes. Everything else should not be in the core module but rather in a seperate plugin (The plugin architecture is not properly implemented yet and will probably arrive in version 1.0.0).

**Comment by christopheschwyzer** [comment]
First, thanks for this great plugin. I really like it. By any chance - any update on the "scroll direction" topic? 
Or is anybody aware of an alternative with similar features? (There are a couple, but I've not seen one that supports `percentagechange` - which is awesome btw.)

**Comment by theborakompanioni** [comment]
@christopheschwyzer Glad you found a workaround (or more precise: Glad you found a better approach!)

**Comment by klihelp** [comment]
thanks @christopheschwyzer 
@theborakompanioni  maybe the native api can be integrated into vissense.

**Comment by theborakompanioni** [comment]
@kilhelp This feature request is now nearly three years old - it seems I wont have time to implement it in the foreseeable future - so I just had to close it. As time is scarce, code changes to VisSense will be bug fixes only. Even the es6 port has not seen the light of day - which would have also been important.

If you're motivated, I am happily accepting pull requests :D
